/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_content_delivery_bucket": "amplifyartaeporte-20220809093258-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-3",
    "aws_content_delivery_url": "https://drid9h69z1s5q.cloudfront.net"
};


export default awsmobile;
